---
name: Geo-Coder-Many
version: 0.25
author:
  - 'Ed Freyfogle <cpan@lokku.com>'
abstract: Module to tie together multiple Geo::Coder::* modules
license: perl
resources:
  license: http://dev.perl.org/licenses/
requires:
  Geo::Coder::Bing: 0.10
  Geo::Coder::Google: 0.06
  Geo::Coder::Googlev3: 0.07
  Geo::Coder::Mapquest: 0.04
  Geo::Coder::Multimap: 0.01
  Geo::Coder::OSM: 0.01
  Geo::Coder::Ovi: 0.01
  Geo::Coder::PlaceFinder: 0.02
  Geo::Coder::SimpleGeo: 0.01
  Geo::Coder::Yahoo: 0.45
  Geo::Distance::XS: 0.08
  HTTP::Request: 5.827
  List::MoreUtils: 0.22
  List::Util: 1.23
  List::Util::WeightedRoundRobin: 0.4
  Net::Ping: 2.33
  Time::HiRes: 1.9711
  perl: 5.010
build_requires:
  Test::Exception: 0
  Test::MockObject: 0
  Test::Pod::Coverage: 0
  Test::Simple: 0
provides:
  Geo::Coder::Many:
    file: lib/Geo/Coder/Many.pm
    version: 0.25
  Geo::Coder::Many::Bing:
    file: lib/Geo/Coder/Many/Bing.pm
  Geo::Coder::Many::Generic:
    file: lib/Geo/Coder/Many/Generic.pm
  Geo::Coder::Many::Google:
    file: lib/Geo/Coder/Many/Google.pm
  Geo::Coder::Many::Googlev3:
    file: lib/Geo/Coder/Many/Googlev3.pm
  Geo::Coder::Many::Mapquest:
    file: lib/Geo/Coder/Many/Mapquest.pm
    version: 0.01
  Geo::Coder::Many::Multimap:
    file: lib/Geo/Coder/Many/Multimap.pm
  Geo::Coder::Many::OSM:
    file: lib/Geo/Coder/Many/OSM.pm
    version: 0.01
  Geo::Coder::Many::Ovi:
    file: lib/Geo/Coder/Many/Ovi.pm
    version: 0.01
  Geo::Coder::Many::PlaceFinder:
    file: lib/Geo/Coder/Many/PlaceFinder.pm
    version: 0.02
  Geo::Coder::Many::Response:
    file: lib/Geo/Coder/Many/Response.pm
  Geo::Coder::Many::Scheduler:
    file: lib/Geo/Coder/Many/Scheduler.pm
  Geo::Coder::Many::Scheduler::OrderedList:
    file: lib/Geo/Coder/Many/Scheduler/OrderedList.pm
  Geo::Coder::Many::Scheduler::Selective:
    file: lib/Geo/Coder/Many/Scheduler/Selective.pm
  Geo::Coder::Many::Scheduler::UniquenessScheduler:
    file: lib/Geo/Coder/Many/Scheduler/UniquenessScheduler.pm
  Geo::Coder::Many::Scheduler::UniquenessScheduler::WRR:
    file: lib/Geo/Coder/Many/Scheduler/UniquenessScheduler/WRR.pm
  Geo::Coder::Many::Scheduler::UniquenessScheduler::WeightedRandom:
    file: lib/Geo/Coder/Many/Scheduler/UniquenessScheduler/WeightedRandom.pm
  Geo::Coder::Many::SimpleGeo:
    file: lib/Geo/Coder/Many/SimpleGeo.pm
    version: 0.01
  Geo::Coder::Many::Util:
    file: lib/Geo/Coder/Many/Util.pm
  Geo::Coder::Many::Yahoo:
    file: lib/Geo/Coder/Many/Yahoo.pm
generated_by: Module::Build version 0.280801
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
